# Generated by Django 6.0.7 on 2026-08-11 14:36

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_order', '0001_initial'),
        ('menu', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupCartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('group_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='group_order.grouporder')),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_cart_items', to='menu.menu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='group_cart_items', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
