# Generated by Django 6.0.7 on 2026-08-11 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_order', '0002_groupcartitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouporder',
            name='budget',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
